/*
    Define the pods that will be used in the Pipeline
*/
podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
        - sleep
        args:
        - 9999999
        volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
      restartPolicy: Never
      volumes:
      - name: kaniko-secret
        secret:
            secretName: dockerhub-creds
            items:
            - key: .dockerconfigjson
              path: config.json
''')

/*
    Define the actual Pipeline
*/
{
  node(POD_LABEL) {

    /*
        At this stage, we build the Jenkins PHPUnit Agent
    */
    stage('Pull Dockerfile from GitHub repository') {
      git url: 'https://github.com/PREngineer/dockerfile-library', branch: 'master'
      container('kaniko') {
        stage('Build and Push') {
          sh '''
            /kaniko/executor --context "`pwd`" --dockerfile=./Jenkins-PHPUnit-Agents/Dockerfile-PHPUnit-10.1.0-PHP-8.1 --destination prengineer/jenkins-agent-php-8.1
          '''
        }
      }
    }
  }
}
